export default {
    'en': {
        loginTitle: 'Login',
        loginUsername: 'UserName',
        loginPassword: 'Password',
        loginButton: 'Login',
        loginClose: 'Close',
        logoutList: 'Logout',
        settingUserGroup: 'User Setting',
        settingFile: 'File Manager',
        settingShare: 'Share Manager',
        settingPersonal: 'Personal Setting',
        settingSystemGroup: 'System Setting',
        settingUsers: 'Users Manager',
        settingSystem: 'System Setting',
    },
    'zh-cn': {
        loginTitle: '登录',
        loginUsername: '用户名',
        loginPassword: '密码',
        loginButton: '登录',
        loginClose: '关闭',
        logoutList: '退出登录',
        settingUserGroup: '个人设置',
        settingFile: '文件管理',
        settingShare: '分享管理',
        settingPersonal: '个人设置',
        settingSystemGroup: '系统设置',
        settingUsers: '用户管理',
        settingSystem: '系统设置',
    },
}